# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ofa76SToODpUl9WZ2zCaEvaKioDleJSa
"""

import streamlit as st
import pandas as pd
from sentiment_model import analyze_sentiment

st.title("📊 Financial News Sentiment Analyzer")

uploaded_file = st.file_uploader("Upload a CSV file with headlines", type="csv")
if uploaded_file:
  df = pd.read_csv(uploaded_file)
  if'headline' in df.columns:
    headlines = df['headline'].tolist()
    st.write("Preview of Headlines")
    st.dataframe(df.head())

    if st.button("analyze Sentiment"):
      with st.spinner("Analyzing..."):
        sentiment_results = analyze_sentiment(headlines)
        df['sentiment'] = [res['label'] for res in sentiment_results]
        st.success("Done!")
        st.write("📈 Sentiment Results")
        st.dataframe(df)


        st.bar_chart(df['sentiment'].value_counts())
  else:
        st.error("CSV must contain a 'headline' column.")

!streamlit run app.py

