# -*- coding: utf-8 -*-
"""sentiment_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aJ3xnvksG9dQRWaDa7yzOM3Mubkq01OZ
"""

from transformers import BertTokenizer, BertForSequenceClassification, pipeline

def finbert():
  model = BertForSequenceClassification.from_pretrained('ProsusAi/finbert',num_labels=3)
  tokenizer = BertTokenizer.from_pretrained('ProsusAi/finbert')
  nlp = pipeline("text-classification", model=model, tokenizer=tokenizer)
  return nlp

def analyze_sentiment(text):
  fb = finbert()
  results = finbert(text)
  return results

